### ISSUE TITLE
프론트 페이지 이슈

### ISSUE THREAD

**Issue by jeongyongs** [nhnacademy-aiot1-5/front-service#138]
## 1. 센서 관리 페이지 > MQTT 센서 관리 > 동작
- 버튼 클릭 시 잘못된 알림창
![Image](https://github.com/nhnacademy-aiot1-5/front-service/assets/98167706/d1da8667-fa30-46ac-ad01-bedd109c0ffc)

## 2. 센서 관리 페이지 > MQTT 센서 관리 > 장치 및 토픽 관리
- 버튼 클릭 시 401 에러

## 3. 일 별 리포트
- 센서 선택 후에도 텍스트가 변경되지 않음
![Image](https://github.com/nhnacademy-aiot1-5/front-service/assets/98167706/323dc6ab-2f14-45b6-a075-1e216360abf9)
- 같은 날이므로 그래프에서 시간만 표시될 수 있도록
![Image](https://github.com/nhnacademy-aiot1-5/front-service/assets/98167706/f8e58910-bbda-4f64-a37f-ce74e143454a)
- 일주일 단위이므로 날짜만 표시될 수 있도록
![Image](https://github.com/nhnacademy-aiot1-5/front-service/assets/98167706/9157bbc9-e9c8-466b-9d9d-5660e6348791)

## 4. 월 별 리포트
- 테이블 버튼 미작동
![Image](https://github.com/nhnacademy-aiot1-5/front-service/assets/98167706/a6bf2b63-66b2-49d6-85ba-68af07a3ab4f)

**Comment by haedanui** [comment]
모두 해결 완료했습니다.
