### ISSUE TITLE
대시보드, 주별리포트, 월별리포트 제외 모든 페이지 나오지 않습니다.

### ISSUE THREAD

**Issue by caboooom** [nhnacademy-aiot1-5/front-service#73]
![image](https://github.com/nhnacademy-aiot1-5/front-service/assets/124178635/73a2e249-003d-4296-a7ec-b91985488603)

**Comment by jeongyongs** [comment]
컨트롤러에서 `/` 로 시작하면 경로에 `//`로 인식됩니다.
view 리턴 시 시작에 있는 `/`를 빼주세요.
